<?php

//This class is needed to start the session and open/close the browser
require_once __DIR__ . '/../wp-core/login.php';

class P4_Split_TwoColumns extends P4_login {

  /**
   * @var \RemoteWebDriver
   */


  public function testSplitTwoColumns()
  {

   	//I log in
	try{
		$this->wpLogin();
	}catch(Exception $e){
		$this->fail('->Failed to log in, verify credentials and URL');
	}

	//Go to pages and create content  
	$this->webDriver->wait(3);
	$pages = $this->webDriver->findElement(
	WebDriverBy::id("menu-pages"));
	$pages->click();
	try{
		$link = $this->webDriver->findElement(
		WebDriverBy::linkText("Add New")
		);
	}catch(Exception $e){
		$this->fail("->Could not find 'Add New' button in Pages overview");
	}
	$link->click();

	//Validate button to add blocks to page is present
	$this->assertContains(
	'Add Post Element',$this->webDriver->findElement(
	WebDriverBy::className('shortcake-add-post-element'))->getText()
	);


	//Enter title of page
	$field	= $this->webDriver->findElement(
	WebDriverBy::id('title-prompt-text')
	);
	$field->click();
	$this->webDriver->getKeyboard()->sendKeys('Test automated - Split Two Column');

	//Click on button to add blocks
	$add = $this->webDriver->findElement(
	WebDriverBy::className("shortcake-add-post-element")
	);
	$add->click();

	//Validate blocks modal window is shown
	$this->assertContains(
	'Insert Post Element',$this->webDriver->findElement(
	WebDriverBy::className('media-frame-title'))->getText()
	);

	//Select Split Two Columns block
	try{
		$ta = $this->webDriver->findElement(
		WebDriverBy::cssSelector("li[data-shortcode='shortcake_split_two_columns']")
		);
		$ta -> click();
	}catch(Exception $e){
		$this->fail("->Failed to select 'Split Two Column' post element");
	}

	//Validate elements are present
	try{
		$this->webDriver->findElement(WebDriverBy::name("select_issue"));
		$this->webDriver->findElement(WebDriverBy::className("select2-selection__rendered"));
		$this->webDriver->findElement(WebDriverBy::name("description"));
		$this->webDriver->findElement(WebDriverBy::name("button_text"));
		$this->webDriver->findElement(WebDriverBy::name("button_link"));
	}catch(Exception $e){
		$this->fail("->Fields corresponding to 'Split Two Columns' block not found");
	}


	//Fill in fields
	$field = $this->webDriver->findElement(
	WebDriverBy::cssSelector("option[value='1222']")
	);
	$field->click();
	$this->webDriver->getKeyboard()->sendKeys('Column 1 Block Test');
	$field = $this->webDriver->findElement(
	WebDriverBy::className("select2-selection__rendered")
	);
	$field->click();
	$this->webDriver->getKeyboard()->sendKeys('ArcticSunrise');
	$field = $this->webDriver->findElement(
	WebDriverBy::name('description')
	);
	$field->click();
	$this->webDriver->getKeyboard()->sendKeys('This is test content generated by an automatic test');


	//Insert block
	try{
		$insert = $this->webDriver->findElement(
		WebDriverBy::className('media-button-insert')
	);
	$insert -> click();
	}catch(Exception $e){
		$this->fail('->Failed to insert element');
	}


	//Publish content
	$this->webDriver->findElement(
	WebDriverBy::id('publish')
	)->click();
	
	//Wait to see successful message
	$this->webDriver->wait(10, 1000)->until(
		WebDriverExpectedCondition::presenceOfElementLocated(
		WebDriverBy::id('message')));
	//Validate I see successful message
	try{
		$this->assertContains(
		'Page published',$this->webDriver->findElement(
		WebDriverBy::id('message'))->getText()
		);
	}catch(Exception $e){
		$this->fail('->Failed to publish content - no sucessful message after saving content');
	}

	//Go to page to validate page contains added block
	$link = $this->webDriver->findElement(
	WebDriverBy::linkText('View page')
	);	
	$link->click();


	// I log out after test
	$this->wpLogout();
  }


  protected function assertElementNotFound($by)
  {
	$this->webDriver->takeScreenshot('reports/screenshots/'.__CLASS__.'.png');
	$els = $this->webDriver->findElements($by);
	if (count($els)) {
		$this->fail("Unexpectedly element was found");
	}
	// increment assertion counter
	$this->assertTrue(true);

  }

}
?>
